### ISSUE TITLE
Searching by custom fields in the link ticket to asset box does does not work.

### ISSUE THREAD

**Issue by pr3sidentspence** [AssetTracker/rt-extension-assettracker#13]
The "Asset Search" box on ticket "Links" pages only works for Name, Type, Status, and Description. Asset custom fields are listed, but if you try to search based on them, no results are found.

**Comment by dentm42** [comment]
The following two patches seem to fix it - although I wasn't expecting that components would be returned along with the object of which they are a component --- I haven't yet dug in to find out if that's a feature or not.  I can see where it would be helpful... I can also see where it would be annoying.  I guess returning too much is better than not enough.  Perhaps Todd can chime in?

Anyway... here's what I've worked out.  Let me know of any issues (or if it works!):

PATCH TO:  local/plugins/RTx-AssetTracker/html/AssetTracker/Elements/AddLinks

<pre>
46a47,49
&gt;     } 
&gt;     elsif (($AssetField eq 'Name') or ($AssetField eq 'Description') or ($AssetField eq 'Status') ) {
&gt;         $Assets-&gt;Limit(FIELD =&gt; $AssetField, VALUE =&gt; $AssetString, OPERATOR =&gt; $AssetOp);
49c52
&lt;         $Assets-&gt;Limit(FIELD =&gt; $AssetField, VALUE =&gt; $AssetString, OPERATOR =&gt; $AssetOp);
---
&gt;         $Assets-&gt;LimitCustomField(CUSTOMFIELD =&gt; $AssetField, VALUE =&gt; $AssetString, OPERATOR =&gt; $AssetOp );
</pre>


PATCH TO: local/plugins/RTx-AssetTracker/html/AssetTracker/Elements/SelectAssets

<pre>
51c51,52
&lt; &lt;option value="CustomField-&lt;% $CF-&gt;Id %&gt;"&gt;&lt;&|/l&&gt;CustomField&lt;/&&gt;: &lt;% $CF-&gt;Name %&gt;
---
&gt; %#&lt;option value="CustomField-&lt;% $CF-&gt;Id %&gt;"&gt;&lt;&|/l&&gt;CustomField&lt;/&&gt;: &lt;% $CF-&gt;Name %&gt;
&gt; &lt;option value="&lt;% $CF-&gt;Id %&gt;"&gt;&lt;&|/l&&gt;CustomField&lt;/&&gt;: &lt;% $CF-&gt;Name %&gt;
</pre>


As usual, run in a non-production environment for testing -- or at least make sure to back up original files first.

**Comment by pr3sidentspence** [comment]
To me that sounds like a feature. :)

Mike

Sent from my iPhone

On 2011-11-17, at 9:54 PM, dentm42
reply@reply.github.com
wrote:

**Comment by pr3sidentspence** [comment]
Tested patch and it works, thanks. Having the owner be searchable would be the icing...

**Comment by dentm42** [comment]
Unfortunately the database schema is a bit different from the Ticket schema and there is no "owners" field like there is in Tickets --- they're actually more like "Watchers" for Tickets.  I didn't get far enough to find out if the query builder already includes this, but I'm guessing not because of the possibility of groups.

Needless to say, searchable owners would be expensive icing (i.e., it's more than a quick hack from what I can tell).

Perhaps a note to the list with a Feature Request will put it on someone's radar.  

It's not something needed for my use of RT+AT like the other patches I did, so I'm not overly motivated to take on that project at this point...

-- Matt

**Comment by pr3sidentspence** [comment]
One possible fix would be a scrip to copy the owner into a custom
field. I'm going to try that.

Mike

Sent from my iPad

On 2011-11-18, at 7:11 AM, dentm42
reply@reply.github.com
wrote:

**Comment by btb** [comment]
applied in #19
