### ISSUE TITLE
Importable spreadsheet error

### ISSUE THREAD

**Issue by pr3sidentspence** [AssetTracker/rt-extension-assettracker#3]
Clicking importable spreadsheet downloads foo.xls.

The contents of foo.xls are as follows:

The following parameter was passed in the call to HTML::Mason::Interp->new() but was not listed in the validation options: cgi_request

**Comment by tbrumm** [comment]
Looks like a missing perl package?

**Comment by pr3sidentspence** [comment]
Hmm... my HTML::Mason HTML::Mason::Request and HTML::Mason::Interp are all
up to date. Do you have any insight into which one may be missing?

**Comment by tbrumm** [comment]
Not 100% at the moment, but i think it is something like Write::Excel or similar <- makes no sense, must be parse::excel!

**Comment by pr3sidentspence** [comment]
I didn't have Spreadsheet::WriteExcel, but I do now; with no change in
result.

**Comment by pr3sidentspence** [comment]
Is it working for you?

**Comment by tbrumm** [comment]
Yes, i tried it last time last week. Works well, i have to check my modules...

**Comment by ghost** [comment]
I have very same problem. What module was missing?

**Comment by pr3sidentspence** [comment]
I never dis find out. Now that rt4 is out I thought I'd do a fresh
install and then migrate the database.

Sent from my iPhone

On 2011-05-07, at 11:26 AM, eembe
reply@reply.github.com
wrote:

**Comment by msfraser** [comment]
I have the same error.

RT-3.8.7 installed from packages on Ubuntu 10.04
AT 2.0.1b installed

I've tried installing libspreadsheet-writeexcel-perl  but this didn't help.

**Comment by pr3sidentspence** [comment]
For those it is working for, do you have custom fields? We have a lot of custom fields, and I'm wondering if it was written to handle them?

**Comment by msfraser** [comment]
Its not working for me an I do have a few custom fields applied to assets. RT 3.8.7

**Comment by ojones117** [comment]
Same issue for me on RT 3.8.7, Ubuntu 10.04. HTML::Mason HTML::Mason::Request and HTML::Mason::Interp are all up to date. Using 3 custom fields. Has anyone had any luck?

**Comment by ghost** [comment]
i also have this issue... RT 3.8.10, Centos5.  I'd think anyone using AT would have plenty of custom fields as that's kind of the point of using it (easy customization, not much default out of the box), right?

ftr, the error i see in my web logs is:

[warning]: Use of uninitialized value in string ne at /opt/rt3/local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Assets_Overlay.pm line 2379

the error we see in the object itself is "The following parameter was passed in the call to HTML::Mason::Interp->new() but was not listed in the validation options: cgi_request".  the string "cgi_request" shows up at line 2741 of the same module.

one weird thing i'm seeing is a block of code starting at line 2721 that appears to be missing a sub name (it's just a lone {, wrapping a block of code)?  i'm not a perl expert but maybe that's the issue here?  a missing function name there?

UPDATE: the docs for HTML::Mason::Interp do not list cgi_request as a valid parameter to the new() constructor so that's the error we're seeing (line 2733 of Assets_Overlay.pm).  I tried just commenting out that parameter, but the new error i get is "Mandatory parameter 'ah' missing in call to RT::Interface::Web::Request->new() "... i'm not sure what the intent of cgi_request is, but maybe that's supposed to be supplying appropriate parameters to the request_class?  I'm pretty far out of my depth here from a coding standpoint, but maybe these findings will lead someone else in the right direction...

**Comment by tbrumm** [comment]
OK Guys, will spent some time to find the module, found my test VM now, just searrching........

**Comment by tbrumm** [comment]
Sorry guys, can't directly find the module, here is a list of all modules installed at the box where the import is running: http://www.my-rt.de/cpan.html

**Comment by tbrumm** [comment]
Could be the following: Spreadsheet::ParseExcel for import together with some XML Modules (it requires XML Excel Exported files)

**Comment by ghost** [comment]
Thanks Torsten,
FYI in the Makefile i used for installing AT it shows "VERSION = 2.0.0_2".  I forgot to mention that... if you're using a different version and things are working fine for you maybe it's a bug introduced as part of that version?  Can you let us know what version you're using?  I can't imagine the current code working at all as-is unless maybe there's another version of HTML::Mason you're using that we're all not, where HTML::Mason::Interp actually accepts a cgi_request parameter... I'm using 1.40 of HTML::Mason.

thanks!
matt

**Comment by tbrumm** [comment]
Hi Matt,
my early tests during development where done with 2.0.0B1 and now i play around with B2 under 4.0 RT. But the HTML::Mason could be change during RT4 upgrade :-(

**Comment by ghost** [comment]
Ok, poking around here in github it looks like a major checkin on 2/9/11 added this code to both the b1 and b2 tags.  I don't see that it existed before than and it hasn't changed since that.  weird!

I'm kind of at a loss here... i looked thru the HTML::Mason::Interp code in CPAN for both the 1.4x and 2.x trees and don't see any reference to a cgi_request parameter, so i don't know that its ever been valid.  Mason 1.4x is now at 1.45 so maybe i'll try upgrading as a shot in the dark...

Torsten, if you could, would you be able to verify that you see the following string in your $RT_HOME/local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Assets_Overlay.pm file starting at line 2740?

request_class        => 'RT::Interface::Web::Request',
cgi_request => new HTML::Mason::FakeApache,
auto_send_headers => 0,

thanks again for your help,
matt

**Comment by tbrumm** [comment]
Got it:

```
my $mason;
my $outbuf = '';
my $data_dir = '';

use HTML::Mason::FakeApache;
sub mason {
    unless ($mason) {
        # user may not have permissions on the data directory, so create a
        # new one
        $data_dir = tempdir(CLEANUP => 1);

        $mason = HTML::Mason::Interp->new(
            #RT::Interface::Web::Handler->DefaultHandlerArgs,
            comp_root => [
                [ local    => $RT::MasonLocalComponentRoot ],
                (map {[ "plugin-".$_->Name =>  $_->ComponentRoot ]} @{RT->Plugins}),
                [ standard => $RT::MasonComponentRoot ]
            ],
            request_class        => 'RT::Interface::Web::Request',
            cgi_request => new HTML::Mason::FakeApache,
            auto_send_headers => 0,

            out_method => \$outbuf,
            autohandler_name => '', # disable forced login and more
            data_dir => $data_dir,
        );
    }
    return $mason;
}
```

-----Ursprüngliche Nachricht-----
Von: mpc512 [mailto:reply@reply.github.com] 
Gesendet: Donnerstag, 8. September 2011 19:29
An: Torsten Brumm
Betreff: Re: [rt-extension-assettracker] Importable spreadsheet error (#3)

Ok, poking around here in github it looks like a major checkin on 2/9/11 added this code to both the b1 and b2 tags.  I don't see that it existed before than and it hasn't changed since that.  weird!

I'm kind of at a loss here... i looked thru the HTML::Mason::Interp code in CPAN for both the 1.4x and 2.x trees and don't see any reference to a cgi_request parameter, so i don't know that its ever been valid.  Mason 1.4x is now at 1.45 so maybe i'll try upgrading as a shot in the dark...

Torsten, if you could, would you be able to verify that you see the following string in your $RT_HOME/local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Assets_Overlay.pm file starting at line 2740?

request_class        => 'RT::Interface::Web::Request',
cgi_request => new HTML::Mason::FakeApache,
auto_send_headers => 0,

thanks again for your help,
matt

##

**Comment by ghost** [comment]
Thanks Torsten,
I have no clue how the "Importable Spreadsheet" link could be working when running that code since it contains the exact same invalid parameter to HTML::Mason::Interp that the rest of us are crashing out on.  I tried upgrading HTML::Mason to 1.43 (could not go to 1.45 due to another module conflict) and as expected I still have the same issue.  I don't think there's any additional troubleshooting I can do from my end at this point, but maybe someone else with more developer skills can check in on this and advise at some point down the road...

matt

**Comment by tbrumm** [comment]
OK, i will try with todd to make it clear, he is at the moment pushing it ready for RT4.x and i will ask him.

Torsten
Am 08.09.2011 um 19:44 schrieb mpc512:

**Comment by ghost** [comment]
Great!  Thanks for that... let me know if Todd needs any additional info from me and I'm happy to provide it...

**Comment by ghost** [comment]
It occurs to me that the actual reason I was trying to create the "importable spreadsheet" was that I just wanted to see the format so I could create one with a bunch of new assets and import it.  Does anyone know if there is some way other than the "Importable spreadsheet" link (documentation?) that I could figure out how the spreadsheet should look based on all my custom fields, etc?  I figure having that info in this thread could help other people running into this same issue as it's being investigated.

thanks,
matt

**Comment by pr3sidentspence** [comment]
I have the latest AT2 as of this date and am now running it with RT4.0.2. There is a new and different error in the importable spreadsheet now:

Global $r object is not available. Set: 
    PerlOptions +GlobalRequest
in httpd.conf at /usr/lib/perl5/5.8.8/CGI.pm line 367.

**Comment by pr3sidentspence** [comment]
I needed to get this working, so I started experimenting. I added

<pre>
PerlOptions +GlobalRequest
</pre>

to httpd.conf and it's working now.

Now.. how do you import the spreadsheet?

**Comment by btb** [comment]
This issue is old and it sounds like a few different problems that have been fixed. feel free to create a new issue for any errors that still occur
